apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: meetadoo-user-api
  name: meetadoo-user-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meetadoo-user-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: meetadoo-user-api
    spec:
      containers:
        - image: gcr.io/meetadoo/meetadoo-user-api:latest
          name: meetadoo-user-api
          env:
            - name: EXAMPLE_ENV_VARIABLE
              value: "example"
          # imagePullPolicy: Never
          resources:
            requests:
              memory: "1Gi"
              cpu: "3"
            limits:
              memory: "3Gi"
              cpu: "3"
          ports:
            - containerPort: 5000
status: {}
