# apiVersion: v1
# kind: Service
# metadata:
#   name: meetadoo-user-api-service
#   labels:
#     app: meetadoo-user-api
# spec:
#   ports:
#     - port: 8080
#       targetPort: 5000
#   selector:
#     app: meetadoo-user-api
#     tier: backend
#   type: LoadBalancer
apiVersion: v1
kind: Ingress
metadata:
  name: meetadoo-user-api-ingresds
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: meetadoo-user-api
              servicePort: 5000
