apiVersion: v1
kind: Service
metadata:
  name: meetadoo-user-api-service
  labels:
    app: meetadoo-user-api
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  selector:
    app: meetadoo-user-api
    # tier: backend
  type: LoadBalancer
